### ISSUE TITLE
Better @Named binding support

### ISSUE THREAD

**Issue by josephlbarnett** [authzee/kotlin-guice#9]
Currently, regular bindings can use `.annotatedWith(Names.named(name))` to do a named binding, but fall back to regular Guice, rather than kotlin-guice after doing so:

`bind<Interface>().annotatedWith(Names.named(name)).to(Implementation::class.java)`

instead of being able to do something like: 

`bind<Interface>().annotatedWith(Names.named(name)).to<Implementation>()`
or, potentially something like:
`bind<Interface>().named(name).to<Implementation>()`

On the Multibinding support, it doesn't appear that named bindings are supported at all, and need to fall back fully to regular Guice:
`Multibinder.newSetBinder(binder(), Interface::class.java, Names.named(name)).addBinding().to(Implementation::class.java)`

instead of being able to do something like:

`KotlinMultibinder.namedSetBinder<Interface>(kotlinBinder, name).addBinding().to<Implementation>()`

**Comment by johnlcox** [comment]
Fixed by #14
